### ISSUE TITLE
Kubeernetes how to enable readinessProbe in Lagom?

### ISSUE THREAD

**Issue by fernandohackbart** [fernandohackbart/bikeride-lagom#171]
```
        readinessProbe:
          httpGet:
            path: "/_status/circuit-breaker/current"
            port: 9000
          initialDelaySeconds: 15
          timeoutSeconds: 5
```
