### ISSUE TITLE
Deploy Bikeride over Kubernetes (not minikube)

### ISSUE THREAD

**Issue by fernandohackbart** [fernandohackbart/bikeride-lagom#182]
After installing Kubernetes directly on top of Centos7 the StorageClasses defined in the PODs does not work anymore

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: jenkins-fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
```

**Comment by fernandohackbart** [comment]
https://github.com/fernandohackbart/ansible-gluster-centos

https://github.com/heketi/heketi/blob/master/doc/admin/install-kubernetes.md

https://github.com/gluster/gluster-kubernetes/blob/master/docs/examples/hello_world/README.md

https://github.com/fernandohackbart/ansible-gluster-centos

**Comment by fernandohackbart** [comment]
``` 
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-gluster
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.40.44:8080"
  restuser: ""
  secretNamespace: ""
  secretName: ""
allowVolumeExpansion: true
```
